# Site
repository: simex05/simex05.github.io
title: Portfolio
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Marco Simeone
#title: Senior Network System Administrator
email: marcosimeone2005@gmail.com
website: simex05.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  simex05
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: simeonemarco
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: CV
  icon: fas fa-id-card
  url: simex05.github.io/images/SimeoneMarco_CV.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Presentazione
about_profile_image: https://media.licdn.com/dms/image/D4D03AQFsuCmSF5yzWA/profile-displayphoto-shrink_200_200/0/1720532974740?e=1726099200&v=beta&t=fS0_3qSMPstg2M07-kLf-881oQo5bnphA-fAnj9YNQk
about_content: | # this will include new lines to allow paragraphs
  Sono un neodiplomato in Informatica e Telecomunicazioni all'IIS Amedeo Avogadro di Torino, con una solida preparazione teorica e pratica in informatica.<br>
  Ho partecipato a varie competizioni, come OliCyber, le Olimpiadi Italiane di Informatica (sia a squadre che individuali) e, più recentemente, CANSAT.<br>
  Queste esperienze mi hanno permesso di acquisire conoscenze ed esperienza sia nell'ambito informatico che in quello progettuale.
  

content:
  - title: Istruzione e formazione # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Diploma di perito in informatica e telecomunicazioni (con voto 93/100)
        caption: 2019 - 2024
        sub_title: Presso l'IIS Amedeo Avogadro di Torino
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Durante i miei studi all'IIS Amedeo Avogadro, oltre ad aver appreso nozioni di informatica e di elettronica di base, ho avuto l'occasione di svolgere diverse attività come competizioni e corsi:
          - Corso HTML-CSS attraverso la piattaforma HackersGen dell'azienda SORINT (2022)
          - Corso LINUX BASE attraverso la piattaforma HackersGen dell'azienda SORINT (2022)
          - Corso LINUX BASH SCRIPTING attraverso la piattaforma HackersGen dell'azienda SORINT (2023)
          - Competizione OliCyber organizzata dal Cybersecurity National Lab (2023 e 2024)
          - Competizione CyberChallenge organizzata dal Cybersecurity National Lab (2023)
          - Competizione OIS ("Olimpiadi di Informatica a Squadre") (2022 e 2023)
          - Competizione OII ("Olimpiadi di Informatica Individuali") (2022 e 2023)
          - Competizione CANSAT organizzato dall'ESERO (programma dell'ESA e dell'ASI) (2024)
          
      - layout: left
        title: Olicyber Training Camp
        caption: 2023
        sub_title: Presso il Cybersecurity National Lab del CINI
        quote: >
          OliCyber sta per "Olimpiadi Italiane di Cybersicurezza" ed è una competizione organizzata dal Cybersecurity National Lab del CINI
        description: | # this will include new lines to allow paragraphs
          L'Olicyber Training Camp è un programma di formazione intensiva con l'obiettivo di formare i partecipanti alla competizione OliCyber, sviluppando le loro competenze tecniche e pratiche nel campo della sicurezza informatica attraverso una settimana di lezioni su crittografia, scripting, network security, web security e software security svolte dai membri della squadra di CTF del Team ITALY. <br>
          Partecipare a questo programma mi ha permesso di sviluppare competenze nell'ambito della sicurezza informatica e di conoscere molte persone da tutta Italia con cui confrontarmi.

  - title: Esperienze lavorative # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Erasmus+
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Presso Asociación Arrabal-AID
        caption: Giugno 2023
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Ho partecipato ad un progetto Erasmus+ della durata di un mese a Malaga (Spagna).
            Durante questa esperienza, ho lavorato per l'Asociación Arrabal-AID progettando e programmando, in team, un quiz-videogame da zero.<br>
            Mi sono occupato del back-end (Java), del front-end (HTML, CSS e JavaScript) e della configurazione del server su cui il videogioco veniva hostato.


  - title: Progetti # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CANSAT con il team AvoVoyagers
        link: cansat.itisavogadro.org
        link_text: cansat.itisavogadro.org
        quote: >
          CANSAT è un progetto educativo internazionale organizzato in Italia dall'ESERO (un programma dell'ESA e dell'ASI) che sfida gli studenti a costruire e lanciare un piccolo satellite delle dimensioni di una lattina. 
        description: | # this will include new lines to allow paragraphs
          Ho progettato, costruito e programmato un CanSat con la squadra AvoVoyagers dell'IIS Amedeo Avogadro di Torino arrivando alla fase nazionale svoltasi a Bologna, presso il campo volo Molinella. <br>
          Durante la fase finale il mini-satellite è stato lanciato con un razzo a 1000m di altezza.<br>
          È stata una gran soddisfazione vedere questo progetto durato mesi essere usato per quello per cui è stato progettato.<br><br>
          <img src="images/IMG_0480.JPG" alt="AvoVoyagers CANSAT>
          

#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.       


#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)
#
#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
